version: '3.9'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    container_name: message-server

  client:
    build:
      context: ./client
    depends_on:
      - server
    container_name: message-client
    environment:
      - SERVER_URL=http://message-server:8080